### ISSUE TITLE
Release on melpa

### ISSUE THREAD

**Issue by DamienCassou** [foretagsplatsen/emacs-js#1]
Could you please add a recipe on melpa? I can do it if you want.

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> Could you please add a recipe on melpa? I can do it if you want.

I'm in vacation - understand (lazy-mode 1), could you do it?

**Comment by DamienCassou** [comment]
Nicolas Petton <notifications@github.com> writes:

> Damien Cassou <notifications@github.com> writes:
>
>> Could you please add a recipe on melpa? I can do it if you want.
>
> I'm in vacation - understand (lazy-mode 1), could you do it?

I need to refactor some stuff: e.g., emacs-js should not use
package-install by default (this should be done by the dependency
mechanism instead). Can you please give me write access to the repo?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> I need to refactor some stuff: e.g., emacs-js should not use
> package-install by default (this should be done by the dependency
> mechanism instead). Can you please give me write access to the repo?

Sure thing.

**Comment by NicolasPetton** [comment]
@DamienCassou If would probably make sense to move the widgetjs package to its own repository.

**Comment by DamienCassou** [comment]
agree

**Comment by NicolasPetton** [comment]
@DamienCassou the gulp integration is also now on MELPA.

**Comment by DamienCassou** [comment]
won't do
