### ISSUE TITLE
The repository we are being redirected to does not actually exist.

### ISSUE THREAD

**Issue by tarsius** [foretagsplatsen/emacs-js#9]
https://gitea.petton.fr/ftgp/emacs does 404.

**Comment by tarsius** [comment]
@DamienCassou, @NicolasPetton I just realized I probably have to mention you by name...

**Comment by DamienCassou** [comment]
Hi @tarsius. There was nothing in this repository for the community, only stuff for our company so we made the repository private. Feel free to cleanup the emacsmirror.

I'm sorry I never received any notification :-(.

**Comment by DamienCassou** [comment]
I updated the README.
